name: composer update

on:
  schedule:
    - cron: '0 7 * * 1' # At 07:00 GMT on Monday. https://crontab.guru/#0_7_*_*_1

jobs:
  composer_update:
    runs-on: ubuntu-latest
    name: Updates composer dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: composer update action
        uses: kawax/composer-update-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
